p8105_hw2_jy3269
================
Jingyi Yao
2022-10-05

``` r
library(tidyverse)
library(readxl)
```

## Problem 1

### 1. Import csv data

``` r
data_1 <- read_csv("./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c")) %>% 
  janitor::clean_names() 

head(data_1)
```

    ## # A tibble: 6 × 32
    ##   division line     station…¹ stati…² stati…³ route1 route2 route3 route4 route5
    ##   <chr>    <chr>    <chr>       <dbl>   <dbl> <chr>  <chr>  <chr>  <chr>  <chr> 
    ## 1 BMT      4 Avenue 25th St      40.7   -74.0 R      <NA>   <NA>   <NA>   <NA>  
    ## 2 BMT      4 Avenue 25th St      40.7   -74.0 R      <NA>   <NA>   <NA>   <NA>  
    ## 3 BMT      4 Avenue 36th St      40.7   -74.0 N      R      <NA>   <NA>   <NA>  
    ## 4 BMT      4 Avenue 36th St      40.7   -74.0 N      R      <NA>   <NA>   <NA>  
    ## 5 BMT      4 Avenue 36th St      40.7   -74.0 N      R      <NA>   <NA>   <NA>  
    ## 6 BMT      4 Avenue 45th St      40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>  
    ## # … with 22 more variables: route6 <chr>, route7 <chr>, route8 <chr>,
    ## #   route9 <chr>, route10 <chr>, route11 <chr>, entrance_type <chr>,
    ## #   entry <chr>, exit_only <chr>, vending <chr>, staffing <chr>,
    ## #   staff_hours <chr>, ada <lgl>, ada_notes <chr>, free_crossover <lgl>,
    ## #   north_south_street <chr>, east_west_street <chr>, corner <chr>,
    ## #   entrance_latitude <dbl>, entrance_longitude <dbl>, station_location <chr>,
    ## #   entrance_location <chr>, and abbreviated variable names ¹​station_name, …

### 2. Clean data

``` r
transit <- data_1 %>%  
  select(line, station_name, station_latitude,station_longitude, route1:route11, entry, vending, entrance_type, ada) %>% 
  mutate(entry=recode(entry,"YES"= TRUE,"NO"= FALSE))

transit
```

    ## # A tibble: 1,868 × 19
    ##    line     station_…¹ stati…² stati…³ route1 route2 route3 route4 route5 route6
    ##    <chr>    <chr>        <dbl>   <dbl> <chr>  <chr>  <chr>  <chr>  <chr>  <chr> 
    ##  1 4 Avenue 25th St       40.7   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ##  2 4 Avenue 25th St       40.7   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ##  3 4 Avenue 36th St       40.7   -74.0 N      R      <NA>   <NA>   <NA>   <NA>  
    ##  4 4 Avenue 36th St       40.7   -74.0 N      R      <NA>   <NA>   <NA>   <NA>  
    ##  5 4 Avenue 36th St       40.7   -74.0 N      R      <NA>   <NA>   <NA>   <NA>  
    ##  6 4 Avenue 45th St       40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ##  7 4 Avenue 45th St       40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ##  8 4 Avenue 45th St       40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ##  9 4 Avenue 45th St       40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ## 10 4 Avenue 53rd St       40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ## # … with 1,858 more rows, 9 more variables: route7 <chr>, route8 <chr>,
    ## #   route9 <chr>, route10 <chr>, route11 <chr>, entry <lgl>, vending <chr>,
    ## #   entrance_type <chr>, ada <lgl>, and abbreviated variable names
    ## #   ¹​station_name, ²​station_latitude, ³​station_longitude

-   Description of the data:

-   the transit data set has : 19 columns(variables) and 1868 rows

-   the dimenison is : 1868, 19

-   the variables are : line, station_name, station_latitude,
    station_longitude, route1, route2, route3, route4, route5, route6,
    route7, route8, route9, route10, route11, entry, vending,
    entrance_type, ada

-   data cleaning steps:

-   read in csv and then change the data type from route8 to route11
    into character

-   unify variable name format using `janitor::clean_names`

-   select the required columns using `select()` in `dplyr`

-   convert the character values in `entry` column into logical values
    (TRUE or FALSE) using `mutate()` and `recode()`

### 3. How many distinct station?

``` r
# method 1
tibble(transit$line,transit$station_name) %>% 
  distinct()
```

    ## # A tibble: 465 × 2
    ##    `transit$line` `transit$station_name`  
    ##    <chr>          <chr>                   
    ##  1 4 Avenue       25th St                 
    ##  2 4 Avenue       36th St                 
    ##  3 4 Avenue       45th St                 
    ##  4 4 Avenue       53rd St                 
    ##  5 4 Avenue       59th St                 
    ##  6 4 Avenue       77th St                 
    ##  7 4 Avenue       86th St                 
    ##  8 4 Avenue       95th St                 
    ##  9 4 Avenue       9th St                  
    ## 10 4 Avenue       Atlantic Av-Barclays Ctr
    ## # … with 455 more rows

### 4. ADA compliant

``` r
transit %>% 
  filter(ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct()
```

    ## # A tibble: 84 × 2
    ##    station_name                   line           
    ##    <chr>                          <chr>          
    ##  1 Atlantic Av-Barclays Ctr       4 Avenue       
    ##  2 DeKalb Av                      4 Avenue       
    ##  3 Pacific St                     4 Avenue       
    ##  4 Grand Central                  42nd St Shuttle
    ##  5 34th St                        6 Avenue       
    ##  6 47-50th Sts Rockefeller Center 6 Avenue       
    ##  7 Church Av                      6 Avenue       
    ##  8 21st St                        63rd Street    
    ##  9 Lexington Av                   63rd Street    
    ## 10 Roosevelt Island               63rd Street    
    ## # … with 74 more rows

### 5. Proportion of entrance without vending

``` r
proportion <- transit %>% 
  filter(vending == "NO") %>% 
  pull(entry) %>% 
  mean()

proportion
```

    ## [1] 0.3770492

### 6. Reform route number and route name

``` r
transit %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A", ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct()
```

    ## # A tibble: 17 × 2
    ##    station_name                  line            
    ##    <chr>                         <chr>           
    ##  1 14th St                       8 Avenue        
    ##  2 168th St - Washington Heights 8 Avenue        
    ##  3 175th St                      8 Avenue        
    ##  4 34th St                       8 Avenue        
    ##  5 42nd St                       8 Avenue        
    ##  6 59th St                       8 Avenue        
    ##  7 Inwood - 207th St             8 Avenue        
    ##  8 West 4th St                   8 Avenue        
    ##  9 World Trade Center            8 Avenue        
    ## 10 Times Square-42nd St          Broadway        
    ## 11 59th St-Columbus Circle       Broadway-7th Ave
    ## 12 Times Square                  Broadway-7th Ave
    ## 13 8th Av                        Canarsie        
    ## 14 Franklin Av                   Franklin        
    ## 15 Euclid Av                     Fulton          
    ## 16 Franklin Av                   Fulton          
    ## 17 Howard Beach                  Rockaway

## Problem 2

### 1. Import Mr. Trash Wheel

``` r
data_2 <- read_excel("./data/Trash Wheel Collection Data.xlsx",range = "A2:N550") 
# select the range that contains data

head(data_2)
```

    ## # A tibble: 6 × 14
    ##   Dumpster Month Year  Date                Weight (ton…¹ Volum…² Plast…³ Polys…⁴
    ##      <dbl> <chr> <chr> <dttm>                      <dbl>   <dbl>   <dbl>   <dbl>
    ## 1        1 May   2014  2014-05-16 00:00:00          4.31      18    1450    1820
    ## 2        2 May   2014  2014-05-16 00:00:00          2.74      13    1120    1030
    ## 3        3 May   2014  2014-05-16 00:00:00          3.45      15    2450    3100
    ## 4        4 May   2014  2014-05-17 00:00:00          3.1       15    2380    2730
    ## 5        5 May   2014  2014-05-17 00:00:00          4.06      18     980     870
    ## 6        6 May   2014  2014-05-20 00:00:00          2.71      13    1430    2140
    ## # … with 6 more variables: `Cigarette Butts` <dbl>, `Glass Bottles` <dbl>,
    ## #   `Grocery Bags` <dbl>, `Chip Bags` <dbl>, `Sports Balls` <dbl>,
    ## #   `Homes Powered*` <dbl>, and abbreviated variable names ¹​`Weight (tons)`,
    ## #   ²​`Volume (cubic yards)`, ³​`Plastic Bottles`, ⁴​Polystyrene

### 2. Clean Mr. Trash Wheel

``` r
mr <- data_2 %>% 
  janitor::clean_names() %>%              # tidy up variable names
  drop_na(dumpster) %>%                   # drop the rows without specific dumpster information
  mutate(sports_balls = as.integer(round(sports_balls,digits = 0)),
         origin = "Mr. Trash Wheel ",.before = "dumpster") %>% 
  unite("ID",origin : dumpster,sep = "")  # a new column named ID to mark the dumpster from Mr.
  
head(mr)
```

    ## # A tibble: 6 × 14
    ##   ID     month year  date                weigh…¹ volum…² plast…³ polys…⁴ cigar…⁵
    ##   <chr>  <chr> <chr> <dttm>                <dbl>   <dbl>   <dbl>   <dbl>   <dbl>
    ## 1 Mr. T… May   2014  2014-05-16 00:00:00    4.31      18    1450    1820  126000
    ## 2 Mr. T… May   2014  2014-05-16 00:00:00    2.74      13    1120    1030   91000
    ## 3 Mr. T… May   2014  2014-05-16 00:00:00    3.45      15    2450    3100  105000
    ## 4 Mr. T… May   2014  2014-05-17 00:00:00    3.1       15    2380    2730  100000
    ## 5 Mr. T… May   2014  2014-05-17 00:00:00    4.06      18     980     870  120000
    ## 6 Mr. T… May   2014  2014-05-20 00:00:00    2.71      13    1430    2140   90000
    ## # … with 5 more variables: glass_bottles <dbl>, grocery_bags <dbl>,
    ## #   chip_bags <dbl>, sports_balls <int>, homes_powered <dbl>, and abbreviated
    ## #   variable names ¹​weight_tons, ²​volume_cubic_yards, ³​plastic_bottles,
    ## #   ⁴​polystyrene, ⁵​cigarette_butts

### 3. Import Professor Trash Wheel

``` r
data_3 <- read_excel("./data/Trash Wheel Collection Data.xlsx",range = "A2:M97",sheet="Professor Trash Wheel")
# select the range that contains data

head(data_3)
```

    ## # A tibble: 6 × 13
    ##   Dumpster Month     Year Date                Weight (…¹ Volum…² Plast…³ Polys…⁴
    ##      <dbl> <chr>    <dbl> <dttm>                   <dbl>   <dbl>   <dbl>   <dbl>
    ## 1        1 January   2017 2017-01-02 00:00:00       1.79      15    1950    6080
    ## 2        2 January   2017 2017-01-30 00:00:00       1.58      15    9540   11230
    ## 3        3 February  2017 2017-02-26 00:00:00       2.32      18    8350    9210
    ## 4        4 February  2017 2017-02-26 00:00:00       3.72      15    8590    1030
    ## 5        5 February  2017 2017-02-28 00:00:00       1.45      15    7830    9950
    ## 6        6 March     2017 2017-03-30 00:00:00       1.71      15    8210   10340
    ## # … with 5 more variables: `Cigarette Butts` <dbl>, `Glass Bottles` <dbl>,
    ## #   `Grocery Bags` <dbl>, `Chip Bags` <dbl>, `Homes Powered*` <dbl>, and
    ## #   abbreviated variable names ¹​`Weight (tons)`, ²​`Volume (cubic yards)`,
    ## #   ³​`Plastic Bottles`, ⁴​Polystyrene

### 4. Clean Professor Trash Wheel

``` r
pro <- data_3 %>% 
  janitor::clean_names() %>%             # tidy up variable names
  drop_na(dumpster) %>%                  # drop rows without specific dumpster information
  mutate(year=as.character(year) ,
         origin = "Professor Trash Wheel ",.before = "dumpster") %>% 
  unite("ID",origin : dumpster,sep = "") # a new column to mark the dumpster from professor

head(pro)
```

    ## # A tibble: 6 × 13
    ##   ID     month year  date                weigh…¹ volum…² plast…³ polys…⁴ cigar…⁵
    ##   <chr>  <chr> <chr> <dttm>                <dbl>   <dbl>   <dbl>   <dbl>   <dbl>
    ## 1 Profe… Janu… 2017  2017-01-02 00:00:00    1.79      15    1950    6080   19700
    ## 2 Profe… Janu… 2017  2017-01-30 00:00:00    1.58      15    9540   11230   17600
    ## 3 Profe… Febr… 2017  2017-02-26 00:00:00    2.32      18    8350    9210   12000
    ## 4 Profe… Febr… 2017  2017-02-26 00:00:00    3.72      15    8590    1030   13000
    ## 5 Profe… Febr… 2017  2017-02-28 00:00:00    1.45      15    7830    9950   16000
    ## 6 Profe… March 2017  2017-03-30 00:00:00    1.71      15    8210   10340   14000
    ## # … with 4 more variables: glass_bottles <dbl>, grocery_bags <dbl>,
    ## #   chip_bags <dbl>, homes_powered <dbl>, and abbreviated variable names
    ## #   ¹​weight_tons, ²​volume_cubic_yards, ³​plastic_bottles, ⁴​polystyrene,
    ## #   ⁵​cigarette_butts

### 5. Combine the 2 datasets

``` r
combined_trash <- bind_rows(mr,pro) # use bind_rows() to combine the 2 datasets
head(combined_trash)
```

    ## # A tibble: 6 × 14
    ##   ID     month year  date                weigh…¹ volum…² plast…³ polys…⁴ cigar…⁵
    ##   <chr>  <chr> <chr> <dttm>                <dbl>   <dbl>   <dbl>   <dbl>   <dbl>
    ## 1 Mr. T… May   2014  2014-05-16 00:00:00    4.31      18    1450    1820  126000
    ## 2 Mr. T… May   2014  2014-05-16 00:00:00    2.74      13    1120    1030   91000
    ## 3 Mr. T… May   2014  2014-05-16 00:00:00    3.45      15    2450    3100  105000
    ## 4 Mr. T… May   2014  2014-05-17 00:00:00    3.1       15    2380    2730  100000
    ## 5 Mr. T… May   2014  2014-05-17 00:00:00    4.06      18     980     870  120000
    ## 6 Mr. T… May   2014  2014-05-20 00:00:00    2.71      13    1430    2140   90000
    ## # … with 5 more variables: glass_bottles <dbl>, grocery_bags <dbl>,
    ## #   chip_bags <dbl>, sports_balls <int>, homes_powered <dbl>, and abbreviated
    ## #   variable names ¹​weight_tons, ²​volume_cubic_yards, ³​plastic_bottles,
    ## #   ⁴​polystyrene, ⁵​cigarette_butts

``` r
tail(combined_trash)
```

    ## # A tibble: 6 × 14
    ##   ID     month year  date                weigh…¹ volum…² plast…³ polys…⁴ cigar…⁵
    ##   <chr>  <chr> <chr> <dttm>                <dbl>   <dbl>   <dbl>   <dbl>   <dbl>
    ## 1 Profe… April 2022  2022-04-07 00:00:00    2.61      15    3900     280    6900
    ## 2 Profe… May   2022  2022-05-05 00:00:00    3.46      15    4400     500    7200
    ## 3 Profe… June  2022  2022-06-10 00:00:00    2.76      15    4900     420    5600
    ## 4 Profe… June  2022  2022-06-21 00:00:00    2.41      10    3600     300    6000
    ## 5 Profe… July  2022  2022-07-05 00:00:00    2.43      15    4500     400    5400
    ## 6 Profe… July  2022  2022-07-18 00:00:00    2.98      15    5000     320    6400
    ## # … with 5 more variables: glass_bottles <dbl>, grocery_bags <dbl>,
    ## #   chip_bags <dbl>, sports_balls <int>, homes_powered <dbl>, and abbreviated
    ## #   variable names ¹​weight_tons, ²​volume_cubic_yards, ³​plastic_bottles,
    ## #   ⁴​polystyrene, ⁵​cigarette_butts

## 6. Description of the data

-   the dimension of **Mr. Trash Wheel** is (547, 14), containing 547
    rows and 14 columns(variables)

-   variables in Mr. Trash Wheel are ID, month, year, date, weight_tons,
    volume_cubic_yards, plastic_bottles, polystyrene, cigarette_butts,
    glass_bottles, grocery_bags, chip_bags, sports_balls, homes_powered

-   I think the key variables in Mr. Trash Wheel are weight_tons,
    volume_cubic_yards because they are the indicators of total weight
    and volume. And sports_ball may also be a variable that is of our
    interest.

-   the dimension of **Professor Trash Wheel** is (94, 13), containing
    94 rows and 13 columns(variables)

-   variables in Professor Trash Wheel are ID, month, year, date,
    weight_tons, volume_cubic_yards, plastic_bottles, polystyrene,
    cigarette_butts, glass_bottles, grocery_bags, chip_bags,
    homes_powered

-   I think the key variables in Professor Trash Wheel are weight_tons,
    volume_cubic_yards because they are the indicators of total weight
    and volume. And the professor dataset does not have the sports_ball
    column.

## 7. Answer to the questions

1.  What was the total weight of trash collected by Professor Trash
    Wheel?

-   the total weight of trash collected by Professor Trash Wheel is
    190.12

2.  What was the total number of sports balls collected by Mr. Trash
    Wheel in 2020?

-   the total number of sports balls collected by Mr. Trash Wheel in
    2020 is 856

## Problem 3

### 1. Import the 3 csv files

``` r
pols_month <- read.csv("./data/pols-month.csv")
head(pols_month)
```

    ##          mon prez_gop gov_gop sen_gop rep_gop prez_dem gov_dem sen_dem rep_dem
    ## 1 1947-01-15        0      23      51     253        1      23      45     198
    ## 2 1947-02-15        0      23      51     253        1      23      45     198
    ## 3 1947-03-15        0      23      51     253        1      23      45     198
    ## 4 1947-04-15        0      23      51     253        1      23      45     198
    ## 5 1947-05-15        0      23      51     253        1      23      45     198
    ## 6 1947-06-15        0      23      51     253        1      23      45     198

``` r
unemployment <- read.csv("./data/unemployment.csv")
head(unemployment)
```

    ##   Year Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec
    ## 1 1948 3.4 3.8 4.0 3.9 3.5 3.6 3.6 3.9 3.8 3.7 3.8 4.0
    ## 2 1949 4.3 4.7 5.0 5.3 6.1 6.2 6.7 6.8 6.6 7.9 6.4 6.6
    ## 3 1950 6.5 6.4 6.3 5.8 5.5 5.4 5.0 4.5 4.4 4.2 4.2 4.3
    ## 4 1951 3.7 3.4 3.4 3.1 3.0 3.2 3.1 3.1 3.3 3.5 3.5 3.1
    ## 5 1952 3.2 3.1 2.9 2.9 3.0 3.0 3.2 3.4 3.1 3.0 2.8 2.7
    ## 6 1953 2.9 2.6 2.6 2.7 2.5 2.5 2.6 2.7 2.9 3.1 3.5 4.5

``` r
snp <- read.csv("./data/snp.csv")
head(snp)
```

    ##     date   close
    ## 1 7/1/15 2079.65
    ## 2 6/1/15 2063.11
    ## 3 5/1/15 2107.39
    ## 4 4/1/15 2085.51
    ## 5 3/2/15 2067.89
    ## 6 2/2/15 2104.50

### 2. Clean the pol-month dataset

``` r
pols <- pols_month %>% 
  janitor::clean_names() %>% 
  separate(mon,into=c("year","month","day")) %>%      # separate the date
  mutate(month = month.abb[as.numeric(month)],        # change name of month into character
         president=ifelse(prez_gop==0,'dem','gop'),   # president takes dem when prez_gop = 0  
         year=as.numeric(year)) %>%                   # change the format of year into dbl
  select(year,month,president,everything(),-prez_gop,-prez_dem,-day) 
  # put year month and president at the front and delete 3 columns specified in the requirement

head(pols)
```

    ##   year month president gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem
    ## 1 1947   Jan       dem      23      51     253      23      45     198
    ## 2 1947   Feb       dem      23      51     253      23      45     198
    ## 3 1947   Mar       dem      23      51     253      23      45     198
    ## 4 1947   Apr       dem      23      51     253      23      45     198
    ## 5 1947   May       dem      23      51     253      23      45     198
    ## 6 1947   Jun       dem      23      51     253      23      45     198

### 3. Clean the snp dataset

``` r
SNP <- snp %>% 
  janitor::clean_names() %>% 
  separate(date,into = c("month","day","year"),sep="/") %>% # separate the date
  mutate(year = as.numeric(year),                           # change year into dbl
         year=ifelse(year<=20,year+2000,year+1900),         # change year into 4 digits
         month = month.abb[as.numeric(month)]) %>%          # change month into character
  select(year,month,close)                                  # set year and month as leading columns


head(SNP)
```

    ##   year month   close
    ## 1 2015   Jul 2079.65
    ## 2 2015   Jun 2063.11
    ## 3 2015   May 2107.39
    ## 4 2015   Apr 2085.51
    ## 5 2015   Mar 2067.89
    ## 6 2015   Feb 2104.50

``` r
tail(SNP)
```

    ##     year month close
    ## 782 1950   Jun 17.69
    ## 783 1950   May 18.78
    ## 784 1950   Apr 17.96
    ## 785 1950   Mar 17.29
    ## 786 1950   Feb 17.22
    ## 787 1950   Jan 17.05

### 4. Clean the unemployment datset

``` r
unemploy <- unemployment %>% 
  pivot_longer(                 # change from wide to longer
    Jan:Dec,
    names_to="month",
    values_to = "unemployment_percentage") %>% 
  rename(year=Year) %>%         # change the name of Year into year to unify with other datasets
  mutate(year= as.numeric(year)) %>% 
  janitor::clean_names()

head(unemploy)
```

    ## # A tibble: 6 × 3
    ##    year month unemployment_percentage
    ##   <dbl> <chr>                   <dbl>
    ## 1  1948 Jan                       3.4
    ## 2  1948 Feb                       3.8
    ## 3  1948 Mar                       4  
    ## 4  1948 Apr                       3.9
    ## 5  1948 May                       3.5
    ## 6  1948 Jun                       3.6

### 5. Join the datasets

``` r
pols_snp <- full_join(pols,SNP)
```

    ## Joining, by = c("year", "month")

``` r
head(pols_snp)
```

    ##   year month president gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem close
    ## 1 1947   Jan       dem      23      51     253      23      45     198    NA
    ## 2 1947   Feb       dem      23      51     253      23      45     198    NA
    ## 3 1947   Mar       dem      23      51     253      23      45     198    NA
    ## 4 1947   Apr       dem      23      51     253      23      45     198    NA
    ## 5 1947   May       dem      23      51     253      23      45     198    NA
    ## 6 1947   Jun       dem      23      51     253      23      45     198    NA

``` r
tail(pols_snp)
```

    ##     year month president gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem
    ## 818 2015   Feb       dem      31      54     245      18      44     188
    ## 819 2015   Mar       dem      31      54     245      18      44     188
    ## 820 2015   Apr       dem      31      54     244      18      44     188
    ## 821 2015   May       dem      31      54     245      18      44     188
    ## 822 2015   Jun       dem      31      54     246      18      44     188
    ## 823 2015   Jul      <NA>      NA      NA      NA      NA      NA      NA
    ##       close
    ## 818 2104.50
    ## 819 2067.89
    ## 820 2085.51
    ## 821 2107.39
    ## 822 2063.11
    ## 823 2079.65

``` r
pols_snp_unemploy <- full_join(pols_snp,unemploy)
```

    ## Joining, by = c("year", "month")

``` r
head(pols_snp_unemploy)
```

    ##   year month president gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem close
    ## 1 1947   Jan       dem      23      51     253      23      45     198    NA
    ## 2 1947   Feb       dem      23      51     253      23      45     198    NA
    ## 3 1947   Mar       dem      23      51     253      23      45     198    NA
    ## 4 1947   Apr       dem      23      51     253      23      45     198    NA
    ## 5 1947   May       dem      23      51     253      23      45     198    NA
    ## 6 1947   Jun       dem      23      51     253      23      45     198    NA
    ##   unemployment_percentage
    ## 1                      NA
    ## 2                      NA
    ## 3                      NA
    ## 4                      NA
    ## 5                      NA
    ## 6                      NA

``` r
tail(pols_snp_unemploy)
```

    ##     year month president gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem
    ## 823 2015   Jul      <NA>      NA      NA      NA      NA      NA      NA
    ## 824 2015   Aug      <NA>      NA      NA      NA      NA      NA      NA
    ## 825 2015   Sep      <NA>      NA      NA      NA      NA      NA      NA
    ## 826 2015   Oct      <NA>      NA      NA      NA      NA      NA      NA
    ## 827 2015   Nov      <NA>      NA      NA      NA      NA      NA      NA
    ## 828 2015   Dec      <NA>      NA      NA      NA      NA      NA      NA
    ##       close unemployment_percentage
    ## 823 2079.65                      NA
    ## 824      NA                      NA
    ## 825      NA                      NA
    ## 826      NA                      NA
    ## 827      NA                      NA
    ## 828      NA                      NA

### 6. Description:

-   the pols data set :

-   it has 822 rows and 9 columns(variables)

-   the year range in pols is 1947, 2015

-   the key variable is `president`,showing which party the president is
    from

-   the SNP data set:

    -   it has 787 rows and 3 columns(variables)
    -   the year range in pols is 1950, 2015
    -   the key variable is `close`, which means the closing values of
        the S&P stock index on the associated date

-   the unemploy data set:

    -   it has 816 rows and 3 columns(variables)
    -   the year range in pols is 1948, 2015
    -   the key variable is `unemployment_percentage`
